export type SHOW_ALL = 'SHOW_ALL';
export const SHOW_ALL: SHOW_ALL = 'SHOW_ALL';

export type SHOW_COMPLETED = 'SHOW_COMPLETED';
export const SHOW_COMPLETED: SHOW_COMPLETED = 'SHOW_COMPLETED';

export type SHOW_ACTIVE = 'SHOW_ACTIVE';
export const SHOW_ACTIVE: SHOW_ACTIVE = 'SHOW_ACTIVE';

export type SHOW_TYPES = SHOW_ALL | SHOW_COMPLETED | SHOW_ACTIVE;
